spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: boarder
    password: boardpass
    url: jdbc:postgresql://localhost:5432/board
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  profiles:
    active: dev

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type:
    descriptor.sql: trace
  org.springframework:
    security: DEBUG

